// src/services/ai/providers/MockProvider.ts
// ─────────────────────────────────────────────────────────────
// Mock AI provider for development, testing, and demos.
//
// Features:
//   • Zero API calls — works offline, costs nothing
//   • Section-aware responses (different text per generation step)
//   • Simulated streaming with configurable delay
//   • Deterministic — same input always produces same output
//   • Instant testConnection() — always succeeds
//
// Activate by setting AI Provider to "Mock — Demo Mode" in
// Configuration → AI Behavior.
// ─────────────────────────────────────────────────────────────

import type {
  IAIProvider,
  AIGenerationRequest,
  AIGenerationResult,
  AIStreamCallback,
  AIConnectionTest,
} from '../IAIProvider';

// ── Canned responses per generation step ID ───────────────────
// Real fix, per direct report: "I have to push back, I never entered
// any data at all... if this isn't coming from seed, then what is
// populating that text?" Traced precisely to two compounding bugs:
//
// 1. This map's keys (admin_header/gross_description/synoptic_summary/
//    ancillary_and_diagnosis) were written against
//    narrativeTemplateConfig.ts's "default_narrative_template" — a
//    template that isn't actually the one in use. The real template
//    ("Gold Standard — General Surgical Pathology", resolved for
//    every case that doesn't have a client-specific override) uses
//    entirely different section IDs, defined in
//    services/reportParts/mockReportPartService.ts:
//    std_body_gross / std_body_microscopic / std_body_ancillary /
//    std_body_diagnosis. None of this map's old keys ever matched
//    any of them.
// 2. Compounding that: resolveSectionId() used to guess the target
//    section by searching for its name as literal text anywhere in
//    the prompt — but every prompt (orchestratorEngine.ts's
//    buildSectionPrompt) always includes the full case-context block
//    with a "─── GROSS DESCRIPTION ───" header, regardless of which
//    section is the actual target. That header is not the same
//    string as the section-under-generation, but the crude substring
//    match couldn't tell the difference — so the "gross_description"
//    key won for every single section, silently.
//
// Fixed on both fronts: AIGenerationRequest now carries a real
// sectionId (see IAIProvider.ts), passed through directly from
// orchestratorEngine.ts's own section.id, which is authoritative —
// no more guessing. This map's keys now match the real, actual
// section IDs, with genuinely distinct, section-appropriate text for
// each (not the same gross-description-shaped paragraph reused
// everywhere).

const MOCK_NARRATIVES: Record<string, string> = {
  std_body_gross:
    'The specimen is received in formalin fixative, appropriately labeled in ' +
    'accordance with the submitted requisition. Gross examination reveals tissue ' +
    'that is adequate for histological evaluation. Representative sections have ' +
    'been submitted for processing per standard laboratory protocol. Block ' +
    'allocation is documented in the gross description worksheet.',

  std_body_microscopic:
    'Sections demonstrate tissue architecture consistent with the submitted ' +
    'specimen type. Cytologic features, including nuclear morphology and ' +
    'mitotic activity, are assessed and documented in the structured synoptic ' +
    'fields. Margin status and lymphovascular involvement, where applicable, ' +
    'are recorded per the synoptic panel rather than restated here. This is ' +
    'placeholder text generated by the Mock provider for demonstration purposes.',

  std_body_ancillary:
    'Ancillary studies performed for this case, including immunohistochemical ' +
    'and molecular testing where indicated, are summarized per the panels ' +
    'ordered and results recorded in the structured data fields. Only tests ' +
    'actually performed for this specimen are reflected. This is placeholder ' +
    'text generated by the Mock provider for demonstration purposes.',

  std_body_diagnosis:
    'A concise anatomic pathology diagnosis is documented per specimen, using ' +
    'standard CAP/RCPath terminology and reflecting the structured synoptic ' +
    'findings recorded for this case. Margin and lymph node status are noted ' +
    'where relevant. This is placeholder text generated by the Mock provider ' +
    'for demonstration purposes.',

  // Fallback for any unrecognised section IDs
  _default:
    'This generation step has been completed using mock data for demonstration ' +
    'purposes. In production, content is generated by the active AI provider ' +
    'from the structured case data and clinical context supplied by the ' +
    'Orchestrator Engine.',
};

// ── Word-by-word streaming delay ──────────────────────────────
// 25ms per word ≈ natural reading speed for demos.
// Set to 0 for unit tests to avoid test timeouts.

const DEFAULT_STREAM_DELAY_MS = 25;

const delay = (ms: number) => new Promise<void>(res => setTimeout(res, ms));

// Real sectionId, when the caller provides it (see AIGenerationRequest
// in IAIProvider.ts) — authoritative, no guessing needed. Falls back to
// the old text-heuristic only if a caller genuinely doesn't pass one,
// so this doesn't hard-fail for any caller not yet updated.

function resolveSectionId(request: AIGenerationRequest): string {
  if (request.sectionId && request.sectionId in MOCK_NARRATIVES) return request.sectionId;

  const known = Object.keys(MOCK_NARRATIVES).filter(k => k !== '_default');
  const lp    = request.prompt.toLowerCase();
  return known.find(id => lp.includes(id.replace(/_/g, ' ').replace('std body ', ''))) ?? '_default';
}

// ── MockProvider ──────────────────────────────────────────────

export class MockProvider implements IAIProvider {
  readonly providerId   = 'mock';
  readonly modelId      = 'mock-v1';
  readonly displayName  = 'Mock — Demo Mode';

  private streamDelayMs: number;

  /**
   * @param streamDelayMs  Milliseconds between word emissions.
   *                       Default 25ms. Set to 0 for instant (unit tests).
   */
  constructor(streamDelayMs = DEFAULT_STREAM_DELAY_MS) {
    this.streamDelayMs = streamDelayMs;
  }

  private getMockText(request: AIGenerationRequest): string {
    const sectionId = resolveSectionId(request);
    return MOCK_NARRATIVES[sectionId] ?? MOCK_NARRATIVES._default;
  }

  // ── generate (non-streaming) ──────────────────────────────

  async generate(request: AIGenerationRequest): Promise<AIGenerationResult> {
    const startMs = Date.now();
    const text    = this.getMockText(request);

    // Small artificial pause so callers don't have to handle
    // synchronous-feeling async in edge cases
    await delay(this.streamDelayMs * 4);

    return {
      text,
      tokensGenerated: text.length,
      providerId:      this.providerId,
      modelId:         this.modelId,
      latencyMs:       Date.now() - startMs,
    };
  }

  // ── generateStream ────────────────────────────────────────

  async generateStream(
    request: AIGenerationRequest,
    onToken: AIStreamCallback,
  ): Promise<AIGenerationResult> {
    const startMs = Date.now();
    const text    = this.getMockText(request);
    const words   = text.split(' ');

    for (const word of words) {
      if (request.abortSignal?.aborted) break;
      onToken(word + ' ');
      if (this.streamDelayMs > 0) await delay(this.streamDelayMs);
    }

    return {
      text,
      tokensGenerated: text.length,
      providerId:      this.providerId,
      modelId:         this.modelId,
      latencyMs:       Date.now() - startMs,
    };
  }

  // ── testConnection ────────────────────────────────────────

  async testConnection(): Promise<AIConnectionTest> {
    return {
      ok:        true,
      message:   'Mock provider ready — no API connection required',
      latencyMs: 0,
    };
  }
}
