<#
.SYNOPSIS
    Rebuilds PathScribe PDF guides and updates guideAssets.ts with new base64.

.DESCRIPTION
    1. Reads Admin_Guide_v0_9_0.pdf and Guide_v0_9_0.pdf from the help folder
    2. Base64-encodes both files
    3. Rewrites src/utils/guideAssets.ts with the new encoded content
    4. Leaves the PDF files in the help folder for reference

.NOTES
    Run from the project root:
        .\Update-GuideAssets.ps1

    Or with explicit paths:
        .\Update-GuideAssets.ps1 -HelpFolder "C:\path\to\public\help" -AssetsFile "C:\path\to\src\utils\guideAssets.ts"
#>

param(
    [string]$HelpFolder = "C:\Users\nimmo\Documents\pathscribe-ai\public\help",
    [string]$AssetsFile = "C:\Users\nimmo\Documents\pathscribe-ai\src\utils\guideAssets.ts"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── Helpers ───────────────────────────────────────────────────────────────────

function Write-Step([string]$msg) {
    Write-Host "`n>> $msg" -ForegroundColor Cyan
}

function Write-Ok([string]$msg) {
    Write-Host "   OK  $msg" -ForegroundColor Green
}

function Write-Warn([string]$msg) {
    Write-Host "   !!  $msg" -ForegroundColor Yellow
}

function Write-Fail([string]$msg) {
    Write-Host "   XX  $msg" -ForegroundColor Red
}

# ── Step 1: Validate paths ─────────────────────────────────────────────────────

Write-Step "Validating paths"

if (-not (Test-Path $HelpFolder)) {
    Write-Fail "Help folder not found: $HelpFolder"
    exit 1
}
Write-Ok "Help folder: $HelpFolder"

if (-not (Test-Path $AssetsFile)) {
    Write-Fail "guideAssets.ts not found: $AssetsFile"
    exit 1
}
Write-Ok "Assets file: $AssetsFile"

# ── Step 2: Locate PDFs ────────────────────────────────────────────────────────

Write-Step "Locating PDF files"

# Accept any filename containing these keywords (case-insensitive)
$adminPdf = Get-ChildItem -Path $HelpFolder -Filter "*.pdf" |
    Where-Object { $_.Name -imatch "admin" } |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1

$userPdf = Get-ChildItem -Path $HelpFolder -Filter "*.pdf" |
    Where-Object { $_.Name -imatch "user|guide" -and $_.Name -inotmatch "admin" } |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1

if (-not $adminPdf) {
    Write-Fail "No admin PDF found in $HelpFolder (expected filename containing 'admin')"
    exit 1
}
if (-not $userPdf) {
    Write-Fail "No user PDF found in $HelpFolder (expected filename containing 'user' or 'guide', not 'admin')"
    exit 1
}

Write-Ok "Admin PDF : $($adminPdf.FullName)  ($([math]::Round($adminPdf.Length/1KB, 1)) KB)"
Write-Ok "User PDF  : $($userPdf.FullName)  ($([math]::Round($userPdf.Length/1KB, 1)) KB)"

# ── Step 3: Encode to base64 ──────────────────────────────────────────────────

Write-Step "Encoding PDFs to base64"

$adminB64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($adminPdf.FullName))
Write-Ok "Admin encoded  ($($adminB64.Length) chars)"

$userB64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($userPdf.FullName))
Write-Ok "User encoded   ($($userB64.Length) chars)"

# ── Step 4: Back up existing guideAssets.ts ───────────────────────────────────

Write-Step "Backing up guideAssets.ts"

$timestamp  = Get-Date -Format "yyyyMMdd_HHmmss"
$backupPath = "$AssetsFile.bak_$timestamp"
Copy-Item -Path $AssetsFile -Destination $backupPath
Write-Ok "Backup: $backupPath"

# ── Step 5: Generate new guideAssets.ts ───────────────────────────────────────

Write-Step "Writing new guideAssets.ts"

$adminName = $adminPdf.Name -replace '\.pdf$', ''
$userName  = $userPdf.Name  -replace '\.pdf$', ''
$generated = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$newContent = @"
// src/utils/guideAssets.ts
// Auto-generated by Update-GuideAssets.ps1 — $generated
// Source PDFs:
//   Admin : $($adminPdf.Name)  ($([math]::Round($adminPdf.Length/1KB, 1)) KB)
//   User  : $($userPdf.Name)  ($([math]::Round($userPdf.Length/1KB, 1)) KB)
// Opened as blob URLs to avoid React Router interception.

const USER_GUIDE_B64  = "$userB64";
const ADMIN_GUIDE_B64 = "$adminB64";

function openPdfBlob(b64: string, filename: string) {
  const bytes = atob(b64);
  const arr   = new Uint8Array(bytes.length);
  for (let i = 0; i < bytes.length; i++) arr[i] = bytes.charCodeAt(i);
  const blob = new Blob([arr], { type: "application/pdf" });
  const url  = URL.createObjectURL(blob);
  const win  = window.open(url, "_blank");
  // Revoke after a short delay so the PDF has time to load
  if (win) setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

export const openUserGuide  = () => openPdfBlob(USER_GUIDE_B64,  "PathScribe_User_Guide.pdf");
export const openAdminGuide = () => openPdfBlob(ADMIN_GUIDE_B64, "PathScribe_Admin_Guide.pdf");
"@

# Write as UTF-8 without BOM (matches TypeScript tooling expectations)
[IO.File]::WriteAllText($AssetsFile, $newContent, [Text.UTF8Encoding]::new($false))

$written = (Get-Item $AssetsFile).Length
Write-Ok "Written: $AssetsFile  ($([math]::Round($written/1KB, 1)) KB)"

# ── Step 6: Sanity check ──────────────────────────────────────────────────────

Write-Step "Sanity check"

$check = Get-Content $AssetsFile -Raw
$adminPresent = $check -match [regex]::Escape($adminB64.Substring(0, 40))
$userPresent  = $check -match [regex]::Escape($userB64.Substring(0, 40))

if ($adminPresent) { Write-Ok "Admin base64 verified in file" }
else               { Write-Warn "Admin base64 NOT found — check the file manually" }

if ($userPresent)  { Write-Ok "User base64 verified in file" }
else               { Write-Warn "User base64 NOT found — check the file manually" }

# ── Done ──────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor White
Write-Host "  1. Vite will hot-reload automatically if dev server is running." -ForegroundColor Gray
Write-Host "  2. If not, restart: npm run dev" -ForegroundColor Gray
Write-Host "  3. Click your initials badge -> User Guide / Admin Guide to verify." -ForegroundColor Gray
Write-Host "  4. Backup saved to: $backupPath" -ForegroundColor Gray
Write-Host ""
